### ISSUE TITLE
Using pixels in CSS

### ISSUE THREAD

**Issue by Karyum** [FACN3/Domain-Finder#27]
https://github.com/FACN3/Domain-Finder/blob/master/style.css#L15

We will need to slowly eliminate the use of pixels in CSS cause it's really bad for responsiveness/mobile compatibility, it's much more encouraged and favored ( sounded poetic there a bit ) to use rem/em.

**Comment by SamiSha99** [comment]
What's the difference between:

rem

and

em

**Comment by NickP123** [comment]
OK thanks. One to review.
