### ISSUE TITLE
"Search not found"

### ISSUE THREAD

**Issue by Amirk390** [FACN3/Domain-Finder#31]
When the search results didnt find anything it returns 'undefined'
in my opinion there should be a message saying "Info not found" or something instead of 
```
IP address: 80.178.83.138
City: Tel Aviv
State/Region: Tel Aviv
Country: Israel
Zipcode:
Timezone: Asia/Jerusalem
Coordinates: 32.0666, 34.765
```

**Comment by NickP123** [comment]
OK - will think about this one and how we can handle this user error.
